version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      quarkus:
        patterns:
          - "io.quarkus*"
          - "io.quarkiverse*"
      orm:
        patterns:
          - "org.hibernate.orm*:*"
      search:
        patterns:
          - "org.hibernate.search:*"
      validator:
        patterns:
          - "org.hibernate.validator:*"
      reactive:
        patterns:
          - "org.hibernate.reactive:*"
      maven-plugins:
        patterns:
          - "*maven*plugin*"
          - "org.apache.maven*:*"
        exclude-patterns:
          - "io.quarkus*"
          - "org.hibernate*"
      test:
        patterns:
          - "org.junit*"
          - "org.apache.logging*"
          - "com.h2database:*"
          - "org.assertj:*"
    ignore:
      - dependency-name: "org.hibernate.orm.tooling:hibernate-enhance-maven-plugin"
      - dependency-name: "org.hibernate:hibernate-core"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "org.hibernate:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.hibernate.*:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "com.h2database:h2"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "com.github.alexcojocaru:elasticsearch-maven-plugin"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.elasticsearch:*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "org.elasticsearch.*:*"
        update-types: [ "version-update:semver-major" ]
