version: '3.7'
services:

    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres:15.4
        environment:
            POSTGRES_PASSWORD: 'rootroot'
            POSTGRES_USER: 'root'
            POSTGRES_DB: 'database'
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: always
        networks:
            - bubble

    migrations:
        image: flyway/flyway:9.16-alpine
        platform: linux/amd64
        container_name: migrations
        hostname: migrations
        command: -url=jdbc:postgresql://postgres:5432/database -user=root -password=rootroot migrate
        depends_on:
            - postgres
        volumes:
            - ./migrations/:/flyway/sql/
        networks:
            - bubble

networks:
    bubble:
        external: true

volumes:
    postgres:
